### ISSUE TITLE
 MongoError: command find requires authentication

### ISSUE THREAD

**Issue by byteshiva** [backmeupplz/DeleteNudesBot#1]
Ami I missing something here.
```
 Bot  is up and running
 MongoError: command find requires authentication
     at MessageStream.messageHandler (/DeleteNudesBot/node_modules/mongodb/lib/cmap/connection.js:268:20)
     at MessageStream.emit (node:events:365:28)
     at processIncomingData (/DeleteNudesBot/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
     at MessageStream._write (/DeleteNudesBot/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
     at writeOrBuffer (node:internal/streams/writable:389:12)
     at _write (node:internal/streams/writable:330:10)
     at MessageStream.Writable.write (node:internal/streams/writable:334:10)
     at Socket.ondata (node:internal/streams/readable:751:22)
     at Socket.emit (node:events:365:28)
     at addChunk (node:internal/streams/readable:314:12)
     at readableAddChunk (node:internal/streams/readable:289:9)
     at Socket.Readable.push (node:internal/streams/readable:228:10)
     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
   ok: 0,
   code: 13,
   codeName: 'Unauthorized'
 } Context {

```

**Comment by byteshiva** [comment]
I found it worked with `admin database` and by passing uri credentials ( username:password).
```
var uri = "mongodb://root:password@172.12.1.3:27017/admin";
```

**Comment by byteshiva** [comment]
this is how I fixed this issue,

In my case I'm using the docker container instance, it can any local instance in your network.
```
var uri = "mongodb://root:password@172.12.1.3:27017/tlgcoin";
```

You run this in Visual Studio MongoDB extension  or via mongo cli
```
use('tlgcoin');

db.createUser(
  {
    user: "tempUser",
    pwd: "password",  
    roles: [
       { role: "readWrite", db: "tlgcoin" }
    ]
  }
)
```
