### ISSUE TITLE
findUser error CastError: Cast to ObjectId failed for value

### ISSUE THREAD

**Issue by byteshiva** [backmeupplz/DeleteNudesBot#2]
findUser error CastError: Cast to ObjectId failed for value "541309441" at path "_id" for model "User"

````
findUser error CastError: Cast to ObjectId failed for value "541309441" at path "_id" for model "User"
[Node]     at model.Query.exec (/home/xyz/telegraf-template/node_modules/mongoose/lib/query.js:4358:21)
[Node]     at model.Query.Query.then (/home/xyz/telegraf-template/node_modules/mongoose/lib/query.js:4450:15)
[Node]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[Node]   messageFormat: undefined,
[Node]   stringValue: '"541309441"',
[Node]   kind: 'ObjectId',
[Node]   value: 541309441,
[Node]   path: '_id',
[Node]   reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
[Node]       at new ObjectID (/home/xyz/telegraf-template/node_modules/bson/lib/bson/objectid.js:59:11)
[Node]       at castObjectId (/home/xyz/telegraf-template/node_modules/mongoose/lib/cast/objectid.js:25:12)
[Node]       at ObjectId.cast (/home/xyz/telegraf-template/node_modules/mongoose/lib/schema/objectid.js:267:12)
[Node]       at ObjectId.SchemaType.applySetters (/home/xyz/telegraf-template/node_modules/mongoose/lib/schematype.js:1075:12)
[Node]       at ObjectId.SchemaType._castForQuery (/home/xyz/telegraf-template/node_modules/mongoose/lib/schematype.js:1510:15)
[Node]       at ObjectId.SchemaType.castForQuery (/home/xyz/telegraf-template/node_modules/mongoose/lib/schematype.js:1500:15)
[Node]       at ObjectId.SchemaType.castForQueryWrapper (/home/xyz/telegraf-template/node_modules/mongoose/lib/schematype.js:1477:20)
[Node]       at cast (/home/xyz/telegraf-template/node_modules/mongoose/lib/cast.js:331:32)
[Node]       at model.Query.Query.cast (/home/xyz/telegraf-template/node_modules/mongoose/lib/query.js:4759:12)
[Node]       at model.Query.Query._castConditions (/home/xyz/telegraf-template/node_modules/mongoose/lib/query.js:1841:10)
[Node]       at model.Query.<anonymous> (/home/xyz/telegraf-template/node_modules/mongoose/lib/query.js:2098:8)
[Node]       at model.Query._wrappedThunk [as _findOne] (/home/xyz/telegraf-template/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
[Node]       at /home/xyz/telegraf-template/node_modules/kareem/index.js:369:33
[Node]       at processTicksAndRejections (node:internal/process/task_queues:78:11)
[Node] }
[Node] TypeError: Cannot read property 'language' of undefined
[Node]     at attachI18N (/home/xyz/telegraf-template/dist/helpers/i18n.js:14:31)
[Node]     at execute (/home/xyz/telegraf-template/node_modules/telegraf/lib/composer.js:458:23)
[Node]     at /home/xyz/telegraf-template/node_modules/telegraf/lib/composer.js:459:27
[Node]     at /home/xyz/telegraf-template/node_modules/telegraf-i18n/lib/i18n.js:104:14
[Node]     at execute (/home/xyz/telegraf-template/node_modules/telegraf/lib/composer.js:458:23)
[Node]     at /home/xyz/telegraf-template/node_modules/telegraf/lib/composer.js:459:27
[Node]     at execute (/home/xyz/telegraf-template/node_modules/telegraf/lib/composer.js:458:23)
[Node]     at /home/xyz/telegraf-template/node_modules/telegraf/lib/composer.js:459:27
[Node]     at /home/xyz/telegraf-template/dist/middlewares/attachUser.js:17:16
[Node]     at Generator.next (<anonymous>)
[Node]     at fulfilled (/home/xyz/telegraf-template/dist/middlewares/attachUser.js:5:58)
[Node]     at processTicksAndRejections (node:internal/process/task_queues:96:5) Context {

```

**Comment by byteshiva** [comment]
fixed this issue 

by changing the model `id to telUserId`

```
export class Chat {
  @prop({ required: true, index: true, unique: true })
  telUserId: number

  @prop({ required: true, default: 'en' })
  language: string
}

// Get Chat model
const ChatModel = getModelForClass(Chat, {
  schemaOptions: { timestamps: true },
})

// Get or create chat
export async function findChat(telUserId: number) {
  let chat = await ChatModel.findOne({ telUserId })
  if (!chat) {
    // Try/catch is used to avoid race conditions
    try {
      chat = await new ChatModel({ telUserId }).save()
    } catch (err) {
      chat = await ChatModel.findOne({ telUserId })
    }
  }
  return chat
}


```
