### ISSUE TITLE
 TelegramError: 400: Bad Request: message can't be deleted for everyone

### ISSUE THREAD

**Issue by byteshiva** [backmeupplz/DeleteNudesBot#4]
Unable to delete messages in the group
```
 TelegramError: 400: Bad Request: message can't be deleted for everyone
     at Telegram.callApi (/home/xyz/DeleteNudesBot/node_modules/telegraf/lib/core/network/client.js:258:19)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async execute (/home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:458:17)
     at async /home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:459:21
     at async execute (/home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:458:17)
     at async /home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:459:21
     at async execute (/home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:458:17)
     at async /home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:459:21
     at async execute (/home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:458:17)
     at async /home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:459:21
     at async execute (/home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:458:17)
     at async /home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:459:21
     at async execute (/home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:458:17)
     at async /home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:459:21
     at async execute (/home/xyz/DeleteNudesBot/node_modules/telegraf/lib/composer.js:458:17) {
   response: {
     ok: false,
     error_code: 400,
     description: "Bad Request: message can't be deleted for everyone"
   },
   on: {
     method: 'deleteMessage',

```

**Comment by byteshiva** [comment]
Found the fix:
basically, I had to navigate in the group to "Manage group" to set bot as administrator. 

![image](https://user-images.githubusercontent.com/10637299/125203158-fd70d700-e294-11eb-9c12-2dd8fe66ef3f.png)

Ref:
https://core.telegram.org/bots/api#deletemessage
